#!/usr/bin/env bash
#MISE description="Update dependencies"

mise install ruby@4.1-dev -f
mise install ruby@jruby-dev -f
mise install ruby@truffleruby-dev -f
mise install

bundle update --bundler
bundle update --all
bundle exec rake clobber

mise run -f install
